spring:
  datasource:
    url: jdbc:h2:mem:brewery-inventory-service;MODE=MYSQL
    username: sa
    password: "{cipher}33bde3f0b8a3c218654bb590cde82249945dc5fc1be761b1826b394b6fc46635"
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  artemis:
    user: artemis-user
    password: "{cipher}ad2c0c2082a365c4824c818db0b4f6b760f6ef438c195bfcfd92082d1d80b0441704774823c6393c3965f7d8f0671c35"

queue:
  inventory:
    add-stock: beer-inventory-add-stock
    allocate-stock: beer-inventory-allocate-stock
    deallocate-stock: beer-inventory-deallocate-stock
    allocate-response: beer-inventory-allocate-response

server:
  port: 8081

eureka:
  username: netflix
  password: "{cipher}b0cb044ba3ebccd70a74dabc001df934d39851c11724918844a4d5e46c87a633"
  client:
    serviceUrl:
      defaultZone: http://${eureka.username}:${eureka.password}@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true