spring:
  datasource:
    url: jdbc:h2:mem:brewery-order-service;MODE=MYSQL
    username: sa
    password: "{cipher}33bde3f0b8a3c218654bb590cde82249945dc5fc1be761b1826b394b6fc46635"
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  artemis:
    user: artemis-user
    password: "{cipher}ad2c0c2082a365c4824c818db0b4f6b760f6ef438c195bfcfd92082d1d80b0441704774823c6393c3965f7d8f0671c35"

queue:
  inventory:
    allocate-stock: beer-inventory-allocate-stock
    deallocate-stock: beer-inventory-deallocate-stock
    allocate-response: beer-inventory-allocate-response
  notification:
    email: beer-notification-send-email
    sms: beer-notification-send-sms
  beer:
    validate: beer-order-validate
    validate-response: beer-validate-response

http-client:
  max-total: 50
  max-per-route: 20
  socket-timeout: PT5S
  idle-timeout: PT60S
  keep-alive-time: PT5S

rest:
  inventory:
    service: "http://localhost:9001/api/v1/inventories/"
    username: beer-inventory-user
    password: "{cipher}fddfadd403c7888c67239e68a473ad8247f5512fc00c60500d469106c96c8afe"
  beer:
    service: "http://localhost:8080/api/v1/beers/"
  customer:
    service: "http://localhost:8083/api/v1/customers/"
server:
  port: 8082

eureka:
  username: netflix
  password: "{cipher}b0cb044ba3ebccd70a74dabc001df934d39851c11724918844a4d5e46c87a633"
  client:
    serviceUrl:
      defaultZone: http://${eureka.username}:${eureka.password}@localhost:8761/eureka
